title: "4D Seismic Hub"
description: "An online abstract of best practices for 4D seismic monitoring"
author: "4D Seismic Hub Working Group"
theme: jekyll-theme-cayman

# Navigation links appearing in the header
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/pages/about"
  - title: "Resources"
    url: "/pages/resources"
  - title: "Case Studies"
    url: "/pages/case-studies"
  - title: "Working Group"
    url: "/pages/working-group"
  - title: "Contribute"
    url: "/pages/contribute"
  - title: "FAQ"
    url: "/pages/faq"

# Enable relative links so that pages work both locally and on GitHub Pages
repository: your-organisation/4D-Seismic-Hub
url: ""
baseurl: ""
markdown: kramdown

# Where to find data and collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default