title: "4D Seismic Hub"
description: "An online abstract of best practices for 4D seismic monitoring"
author: "4D Seismic Hub Working Group"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-include-cache

# Navigation is now defined in `_data/navigation.yml`.

# Enable relative links so that pages work both locally and on GitHub Pages
repository: your-organisation/4D-Seismic-Hub
url: ""
baseurl: ""
markdown: kramdown

# Where to find data and collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default